=== AndreeaStati/Psychology-Website/continut/resurse/persoane.dtd
<!ELEMENT persoane (persoana+)>
<!ELEMENT persoana (nume, prenume, varsta, adresa, telefon, studii)>
<!ATTLIST persoana id CDATA #REQUIRED>
<!ELEMENT nume (#PCDATA)>
<!ELEMENT prenume (#PCDATA)>
<!ELEMENT varsta (#PCDATA)>
<!ELEMENT adresa (strada, numar, localitate, judet, tara)>
<!ELEMENT strada (#PCDATA)>
<!ELEMENT numar (#PCDATA)>
<!ELEMENT localitate (#PCDATA)>
<!ELEMENT judet (#PCDATA)>
<!ELEMENT tara (#PCDATA)>
<!ELEMENT telefon (#PCDATA)>
<!ELEMENT studii (universitate, facultate, oras)>
<!ELEMENT universitate (#PCDATA)>
<!ELEMENT facultate (#PCDATA)>
<!ELEMENT oras (#PCDATA)>

=== AndreeaStati/Psychology-Website/continut/resurse/persoane.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!-- <!DOCTYPE persoane SYSTEM "persoane.dtd"> -->
<persoane xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="persoane.xsd">

<!-- <persoane> -->
    <persoana id="1">
        <nume>Popescu</nume>
        <prenume>Ion</prenume>
        <varsta>23</varsta>
        <adresa> 
            <strada>Vasile Petrescu</strada>
            <numar>19</numar>
            <localitate>Iasi</localitate>
            <judet>Iasi</judet>
            <tara>Romania</tara>
        </adresa>
        <telefon>0751789456</telefon>
        <studii>
            <universitate>Universitatea Alexandru Ioan Cuza</universitate>
            <facultate>Facultatea de Psihologie</facultate>
            <oras>Iasi</oras>
        </studii>
    </persoana>

    <persoana id="2">
        <nume>Ionescu</nume>
        <prenume>Andrei</prenume>
        <varsta>35</varsta>
        <adresa> 
            <strada>Bulevardul Mihai Eminescu</strada>
            <numar>19</numar>
            <localitate>Targu Neamt</localitate>
            <judet>Neamt</judet>
            <tara>Romania</tara>
        </adresa>
        <telefon>0742123456</telefon>
        <studii>
            <universitate>Universitatea din Bucuresti</universitate>
            <facultate>Facultatea de Psihologie și Științele Educației</facultate>
            <oras>Bucuresti</oras>
        </studii>
    </persoana>

    <persoana id="3">
        <nume>Popovici</nume>
        <prenume>Ioana</prenume>
        <varsta>46</varsta>
        <adresa> 
            <strada>Bulevardul Sperantei</strada>
            <numar>2</numar>
            <localitate>Dej</localitate>
            <judet>Cluj</judet>
            <tara>Romania</tara>
        </adresa>
        <telefon>071234593</telefon>
        <studii>
            <universitate>Universitatea Babeș-Bolyai</universitate>
            <facultate>Facultatea de Psihologie si Stiinte ale Educatiei</facultate>
            <oras>Cluj Napoca</oras>
        </studii>
    </persoana>

</persoane>
